
agregator-memcached:
  image: phpdockerio/memcached:latest
  container_name: agregator-memcached

agregator-mailhog:
  image: phpdockerio/mailhog:latest
  container_name: agregator-mailhog
  ports:
    - "8112:8025"

agregator-mysql:
  image: mysql:5.7
  container_name: agregator-mysql
  volumes:
      - ../volumes/agregator-mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123
    - MYSQL_DATABASE=agregator
    - MYSQL_USER=123
    - MYSQL_PASSWORD=123

agregator-webserver-front:
  image: phpdockerio/nginx:latest
  container_name: agregator-webserver-front
  volumes:
      - ../source:/var/www/agregator
      - ./nginx/agregator-webserver-front/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8110:80"
  links:
   - agregator-php-fpm


agregator-webserver-back:
  image: phpdockerio/nginx:latest
  container_name: agregator-webserver-back
  volumes:
      - ../source:/var/www/agregator
      - ./nginx/agregator-webserver-back/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8111:80"
  links:
   - agregator-php-fpm

agregator-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: agregator-php-fpm
  volumes:
    - ../source:/var/www/agregator
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
  links:
    - agregator-memcached
    - agregator-mailhog
    - agregator-mysql
